### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /app/npm-packages/convex/src/cli/index.ts

### ISSUE THREAD

**Issue by benwyrosdick** [get-convex/convex-backend#1]
I ran the steps in the prerequisites then got this when running `just run-local-backend`

```
Error: Failed to run convex deploy:

  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /app/npm-packages/convex/src/cli/index.ts
      at new NodeError (node:internal/errors:405:5)
      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:136:11)
      at defaultGetFormat (node:internal/modules/esm/get_format:182:36)
      at defaultLoad (node:internal/modules/esm/load:101:20)
      at nextLoad (node:internal/modules/esm/hooks:864:28)
      at load (/app/npm-packages/common/temp/node_modules/.pnpm/ts-node@10.9.1_6g2fuyrptaiaimsu354vnqmomu/node_modules/ts-node/dist/child/child-loader.js:19:122)
      at nextLoad (node:internal/modules/esm/hooks:864:28)
      at Hooks.load (node:internal/modules/esm/hooks:447:26)
      at MessagePort.handleMessage (node:internal/modules/esm/worker:196:24)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20) {
    code: 'ERR_UNKNOWN_FILE_EXTENSION'
  }
```

**Comment by benwyrosdick** [comment]
started over and got it working in a docker instance

**Comment by dhowe** [comment]
Same problem here, running convex-backend on ubuntu 18.04 with node 18.20.2

  ```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/dhowe/git/convex-backend/npm-packages/convex/src/cli/index.ts
      at new NodeError (node:internal/errors:405:5)
      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:136:11)
      at defaultGetFormat (node:internal/modules/esm/get_format:182:36)
      at defaultLoad (node:internal/modules/esm/load:101:20)
      at nextLoad (node:internal/modules/esm/hooks:864:28)
      at load (/home/dhowe/git/convex-backend/npm-packages/common/temp/node_modules/.pnpm/ts-node@10.9.1_vuqh3gt2zvtpvbtbczhekraj64/node_modules/ts-node/dist/child/child-loader.js:19:122)
      at nextLoad (node:internal/modules/esm/hooks:864:28)
      at Hooks.load (node:internal/modules/esm/hooks:447:26)
      at MessagePort.handleMessage (node:internal/modules/esm/worker:196:24)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20) {
    code: 'ERR_UNKNOWN_FILE_EXTENSION'
  }
```

**Comment by dhowe** [comment]
Note for anyone else with this problem: downgrading to 18.17.0 fixed this issue for me - not sure what the maximum working version is, but node 18.20.2 and above will not work at present

**Comment by nipunn1313** [comment]
yeah - the supported node version is in the `.nvmrc`. From the instructions:

```
To run the Convex CLI:

[Node.js](https://nodejs.org/en)
Make sure you have the version specified in .nvmrc
We recommend installing Node.js via [nvm](https://github.com/nvm-sh/nvm#installing-and-updating).
Run nvm use from the root of the repo.
```
